name = "Bnc"
uuid = "b532a4b1-2c45-4c12-bcaf-8695372aa40c"
authors = ["Qinguo Liu"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
